[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn langgraph_app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[deploy.variables]
PORT = "8000" 